require 'mr/models/movie'
require 'mr/models/tag'
require 'mr/models/category'
require 'mr/models/movie_category'
require 'mr/models/movie_tags'
require 'mr/models/movie_ratings'
require 'mr/models/movies_similarity'